### ISSUE TITLE
Embed Creator Link Problem

### ISSUE THREAD

**Issue by mehmetcanfarsak** [SlumberDemon/SleepyTools#1]
Hi,
I have tried to test a url in Embed Creator without https:// which is www.repetiti.com

After generating url it can't redirect to the website url I have provided
https://sleepy.deta.dev/card/gcj9pbzosxho

I have also tested  Link Shortener, It checks url and seems no problem

**Comment by SlumberDemon** [comment]
I'll check it out now!

**Comment by SlumberDemon** [comment]
For the redirect to work please make sure to include the https! That should fix all the issues!
